version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
#    working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.rootpasswd.
      - MYSQL_DATABASE=horse_racing_simulator
      - MYSQL_USER=race_user
      - MYSQL_PASSWORD=.userpasswd
    ports:
      - "8082:3306"
  website:
    container_name: hrsgame
    image: tut:php_img
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80